spring:
  profiles:
    include: dao
  application:
    name: seed-blog
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 5MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 7777


